# Generated by Django 4.2 on 2023-04-30 13:00

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to=api.models.user_image_file_path),
        ),
    ]
