# Generated by Django 4.2 on 2023-05-02 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tag_exercise_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
    ]
